version: '2'
services:
  howdoibot:
    image: matcom/howdoi
    build: 
      context: "."
    ports:
      - "8443:5000"


    restart: always

    command: python3 howdoibot.py


    volumes:
      - .:/home/howdoibot
